version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    environment:
      APP_ENV: testing
    working_directory: ~/Triangle-Pos/src/Services/Store
    steps:
      - checkout:
          path: ~/Triangle-Pos
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test