apiVersion: v1
kind: Namespace
metadata:
  name: triangle-microservices

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-configmap
  namespace: triangle-microservices
data:
  APP_ENV: development
  DATABASE_URL: "sqlite:///dev.db"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  namespace: triangle-microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      name: store-pod
      labels:
        app: store
    spec:
      containers:
      - name: store-app
        image: fychin/triangle-store:dev
        envFrom:
        - configMapRef:
            name: microservices-configmap
        ports:
        - name: http-port
          containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: store-svc
  namespace: triangle-microservices
spec:
  type: ClusterIP
  selector:
    app: store
  ports:
  - port: 80
    targetPort: 8000